### PR TITLE
Removes obsolete independent_bn_bias argument

### PR DESCRIPTION
**Pull request by MaxFBurg**
Addressing https://github.com/sinzlab/neuralpredictors/issues/219

### CODE REVIEW

**Comment by pollytur** [comment]
I would keep it on pause while the examples in the [notebooks](https://github.com/sinzlab/neuralpredictors/blob/main/notebooks/example_sysident_models.ipynb) folder are not updated because currently there is [nnsysident](https://github.com/sinzlab/nnsysident) there and it actually uses this argument

**Comment by pollytur** [comment]
After discussing we decided to remove the example later and in the repositories, who depend on this parameter, they might specify the commit to inherit. There is the `independent_bn_bias` in the 3d core, but this should be refactored anyway

**Review by pollytur — DISMISSED** [review]

**Comment by MaxFBurg** [comment]
I will refactor conv3d cores accordingly after #226 was approved/merged

**Comment by MaxFBurg** [comment]
Merge #221 226 before merging this PR to avoid merge conflicts

**Comment by pollytur** [comment]
@MaxFBurg I guess its now black and should be fine after
Thanks for solving the merge conflict!

**Review by pollytur — APPROVED** [review]

**Pull request merged**
